import type { Locale } from "@/lib/locale"

const calculatorCopy = {
  en: {
    badgeInternal: "Internal",
    title: "Calculator",
    lock: "Lock",
    unlock: "Unlock",
    passwordGate: {
      description:
        "Password-protected internal estimate tool. Not intended for public sharing.",
      enterPassword: "Enter password",
      passwordLabel: "Password",
      incorrectPassword: "Incorrect password.",
    },
    headerDescription:
      "Fee schedule reference and quick estimates based on the published maximum fee table.",
    managementPanel: {
      title: "Annual management fees",
      description: "Calculated on portfolio value and billed quarterly.",
      badge: "Quarterly",
      portfolioValue: "Portfolio value (USD)",
      upTo: (maxLabel: string) => `Up to ${maxLabel}`,
      portfolioSliderAria: "Portfolio value slider",
      blendedTitle: "Blended tiers",
      blendedDescription: "Optional progressive calculation.",
      blendedAria: "Toggle blended tiers",
      perQuarter: "per quarter",
      quarterlyRecurring: "Quarterly recurring",
      annualisedRecurring: "Annualised recurring",
      max: "Max",
    },
    tradingPanel: {
      title: "Trading & execution",
      description: "Add your trades to estimate transactional costs.",
      tradeListPeriod: "Trade list period",
      tradeListPeriodHelp: "Used for annualised totals.",
      periodPlaceholder: "Select period",
      periods: {
        "one-time": "One-time",
        monthly: "Monthly",
        quarterly: "Quarterly",
        annual: "Annual",
      },
      table: {
        tradeType: "Trade type",
        valueContracts: "Value / contracts",
        trades: "Trades",
        feePerTrade: "Fee / trade",
        total: "Total",
        actions: "Actions",
        empty: "Add a trade line to start estimating.",
        addLine: "Add line",
      },
      selectTradeTypePlaceholder: "Select trade type",
      contractType: "Contract type",
      contractTypePlaceholder: "Contract type",
      contractsPerTrade: "Contracts per trade",
      tradeValueUsd: "Trade value (USD)",
      rateOverride: "Rate override",
      overrideRatePercentAria: "Override rate percent",
      numberOfTradesAria: "Number of trades",
      removeLineAria: "Remove trade line",
      minApplied: "min applied",
      options: "Options",
      futures: "Futures",
      tradingTotal: "Trading total",
    },
    operationalPanel: {
      title: "Operational & service",
      description: "Add account and administrative costs.",
      badge: "Mixed",
      depositsValue: "Deposits value (USD)",
      depositAccounts: "Deposit accounts",
      administrationAccounts: "Administration (annual) · accounts",
      onboardingCount: "Complex onboarding · count",
      cashTransfersCount: "Cash transfers (annual) · count",
      passThroughExpenses: "Pass-through expenses (USD)",
      annualServiceFees: "Annual service fees",
      oneOffAtCost: "One-off + at cost",
    },
    summaryPanel: {
      title: "Summary",
      description: "Totals are estimates for internal scoping only.",
      quarterlyRecurring: "Quarterly recurring (management)",
      annualRecurring: "Annual recurring (management + service)",
      transactionalTotal: "Transactional total (trades + transfers)",
      annualisedTransactional: (periodLabel: string) =>
        `Annualised transactional (${periodLabel})`,
      oneOffAtCost: "One-off + at cost",
      annualisedAllIn: "Annualised all-in (excl. one-off)",
      footerNote:
        "The fee tables on the left are the reference maximum fee schedule. This estimator applies minimums where stated and uses the selected trade list period to annualise transactional totals.",
    },
    feeTables: {
      serviceType: "Service type",
      assetTierUsd: "Asset / tier (USD)",
      annualRate: "Annual rate",
      minimumFeeUsd: "Minimum fee (USD)",
      frequency: "Frequency",
      assetClass: "Asset class",
      regionDetail: "Region / detail",
      tradeValueTierUsd: "Trade value tier (USD)",
      rateFee: "Rate / fee",
      minimumPerTxUsd: "Minimum per tx (USD)",
      feeCategory: "Fee category",
      description: "Description",
      minimumFlatFee: "Minimum / flat fee",
    },
    feeSections: {
      "annual-management": {
        title: "Annual management fees",
        description:
          "Recurring oversight, custody, and advisory fees for your portfolio. Rates are tiered by total assets under management and billed quarterly.",
      },
      "trading-execution": {
        title: "Trading & execution costs",
        description:
          "Transactional fees applied when buying or selling securities. Rates vary by market, asset class, and trade value tier.",
      },
      "operational-service": {
        title: "Operational & service fees",
        description:
          "Fixed and administrative costs for account onboarding, maintenance, transfers, and pass-through third-party charges.",
      },
    },
    frequencies: {
      Quarterly: "Quarterly",
      Annual: "Annual",
      "Per transaction": "Per transaction",
      "Flat fee": "Flat fee",
      "As incurred": "As incurred",
    },
  },
  ru: {
    badgeInternal: "Внутреннее",
    title: "Калькулятор",
    lock: "Закрыть",
    unlock: "Открыть",
    passwordGate: {
      description:
        "Внутренний инструмент для оценок, защищённый паролем. Не предназначен для публичного распространения.",
      enterPassword: "Введите пароль",
      passwordLabel: "Пароль",
      incorrectPassword: "Неверный пароль.",
    },
    headerDescription:
      "Справочник по максимальным комиссиям и быстрые оценки по опубликованной таблице.",
    managementPanel: {
      title: "Годовые комиссии за управление",
      description: "Расчёт по стоимости портфеля, выставление — ежеквартально.",
      badge: "Квартально",
      portfolioValue: "Стоимость портфеля (USD)",
      upTo: (maxLabel: string) => `До ${maxLabel}`,
      portfolioSliderAria: "Слайдер стоимости портфеля",
      blendedTitle: "Смешанные уровни",
      blendedDescription: "Опциональный прогрессивный расчёт.",
      blendedAria: "Переключить смешанные уровни",
      perQuarter: "за квартал",
      quarterlyRecurring: "Ежеквартально",
      annualisedRecurring: "В пересчёте на год",
      max: "Макс.",
    },
    tradingPanel: {
      title: "Торги и исполнение",
      description: "Добавьте сделки, чтобы оценить транзакционные расходы.",
      tradeListPeriod: "Период списка сделок",
      tradeListPeriodHelp: "Используется для годовой оценки.",
      periodPlaceholder: "Выберите период",
      periods: {
        "one-time": "Разово",
        monthly: "Ежемесячно",
        quarterly: "Ежеквартально",
        annual: "Ежегодно",
      },
      table: {
        tradeType: "Тип сделки",
        valueContracts: "Сумма / контракты",
        trades: "Сделки",
        feePerTrade: "Комиссия / сделка",
        total: "Итого",
        actions: "Действия",
        empty: "Добавьте строку сделки для расчёта.",
        addLine: "Добавить строку",
      },
      selectTradeTypePlaceholder: "Выберите тип сделки",
      contractType: "Тип контракта",
      contractTypePlaceholder: "Тип контракта",
      contractsPerTrade: "Контрактов на сделку",
      tradeValueUsd: "Сумма сделки (USD)",
      rateOverride: "Переопределение ставки",
      overrideRatePercentAria: "Переопределить ставку (в процентах)",
      numberOfTradesAria: "Количество сделок",
      removeLineAria: "Удалить строку сделки",
      minApplied: "применён минимум",
      options: "Опционы",
      futures: "Фьючерсы",
      tradingTotal: "Итого по торгам",
    },
    operationalPanel: {
      title: "Операционные и сервисные",
      description: "Добавьте затраты на обслуживание счёта и администрирование.",
      badge: "Смешанные",
      depositsValue: "Сумма депозитов (USD)",
      depositAccounts: "Депозитных счетов",
      administrationAccounts: "Администрирование (год) · счетов",
      onboardingCount: "Сложный онбординг · кол-во",
      cashTransfersCount: "Денежные переводы (год) · кол-во",
      passThroughExpenses: "Расходы at cost (USD)",
      annualServiceFees: "Годовые сервисные комиссии",
      oneOffAtCost: "Разовые + at cost",
    },
    summaryPanel: {
      title: "Итог",
      description: "Итоги — только для внутренней оценки.",
      quarterlyRecurring: "Ежеквартально (управление)",
      annualRecurring: "В год (управление + сервис)",
      transactionalTotal: "Транзакции (сделки + переводы)",
      annualisedTransactional: (periodLabel: string) =>
        `Транзакции в годовом выражении (${periodLabel})`,
      oneOffAtCost: "Разовые + at cost",
      annualisedAllIn: "All-in в год (без разовых)",
      footerNote:
        "Таблицы комиссий слева — справочник максимальных ставок. Этот расчёт применяет минимумы там, где они указаны, и использует выбранный период списка сделок для годовой оценки транзакционных расходов.",
    },
    feeTables: {
      serviceType: "Услуга",
      assetTierUsd: "Актив / уровень (USD)",
      annualRate: "Годовая ставка",
      minimumFeeUsd: "Минимум (USD)",
      frequency: "Периодичность",
      assetClass: "Класс активов",
      regionDetail: "Регион / детали",
      tradeValueTierUsd: "Уровень суммы (USD)",
      rateFee: "Ставка / комиссия",
      minimumPerTxUsd: "Мин. за сделку (USD)",
      feeCategory: "Категория",
      description: "Описание",
      minimumFlatFee: "Минимум / фикс.",
    },
    feeSections: {
      "annual-management": {
        title: "Годовые комиссии за управление",
        description:
          "Периодические комиссии за управление, хранение и консультации. Ставки зависят от объёма активов под управлением и выставляются ежеквартально.",
      },
      "trading-execution": {
        title: "Торги и исполнение — расходы",
        description:
          "Транзакционные комиссии при покупке/продаже ценных бумаг. Ставки зависят от рынка, класса активов и уровня суммы сделки.",
      },
      "operational-service": {
        title: "Операционные и сервисные комиссии",
        description:
          "Фиксированные и административные расходы: онбординг, обслуживание счёта, переводы и сторонние расходы pass-through.",
      },
    },
    frequencies: {
      Quarterly: "Ежеквартально",
      Annual: "Ежегодно",
      "Per transaction": "За транзакцию",
      "Flat fee": "Фикс.",
      "As incurred": "По факту",
    },
  },
} as const

export function getCalculatorCopy(locale: Locale) {
  return calculatorCopy[locale]
}
